create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     username varchar(254) not null unique,
    nickname varchar(128) not null,
    password_hash varchar(255) not null,
    role varchar(32) not null, -- admin / viewer
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists libraries (
                                         id bigint generated by default as identity primary key,
                                         name varchar(128) not null,
    description text,
    library_type varchar(32) not null, -- mixed / movie / series
    metadata_language varchar(32) not null default 'zh-CN',
    root_path text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists user_library_access (
                                                   user_id bigint not null references users(id) on delete cascade,
    library_id bigint not null references libraries(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, library_id)
    );

create index if not exists idx_user_library_access_library_id on user_library_access(library_id);

create table if not exists user_sessions (
                                             token varchar(128) primary key,
    user_id bigint not null references users(id) on delete cascade,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
    );

create index if not exists idx_user_sessions_user_id on user_sessions(user_id);
create index if not exists idx_user_sessions_expires_at on user_sessions(expires_at);

create table if not exists native_client_sessions (
                                                      id bigint generated by default as identity primary key,
                                                      user_id bigint not null references users(id) on delete cascade,
    access_token_hash varchar(128) not null unique,
    refresh_token_hash varchar(128) not null unique,
    access_token_expires_at timestamptz not null,
    refresh_token_expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_used_at timestamptz not null default now(),
    user_agent text,
    device_name varchar(128),
    client_type varchar(32) not null default 'native'
    );

create index if not exists idx_native_client_sessions_user_id on native_client_sessions(user_id);
create index if not exists idx_native_client_sessions_access_token_hash on native_client_sessions(access_token_hash);
create index if not exists idx_native_client_sessions_refresh_token_hash on native_client_sessions(refresh_token_hash);
create index if not exists idx_native_client_sessions_refresh_token_expires_at on native_client_sessions(refresh_token_expires_at);
create index if not exists idx_native_client_sessions_revoked_at on native_client_sessions(revoked_at);

create table if not exists native_client_used_refresh_tokens (
                                                                 token_hash varchar(128) primary key,
                                                                 session_id bigint not null references native_client_sessions(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now()
    );

create index if not exists idx_native_client_used_refresh_tokens_session_id on native_client_used_refresh_tokens(session_id);
create index if not exists idx_native_client_used_refresh_tokens_user_id on native_client_used_refresh_tokens(user_id);

create table if not exists scan_jobs (
                                         id bigint generated by default as identity primary key,
                                         library_id bigint not null references libraries(id) on delete cascade,
    status varchar(32) not null, -- pending / running / success / failed
    phase varchar(32), -- discovering / processing / finalizing / finished
    total_files integer not null default 0,
    scanned_files integer not null default 0,
    reused_files integer not null default 0,
    local_analyzed_files integer not null default 0,
    local_committed_files integer not null default 0,
    remote_completed_files integer not null default 0,
    progress_percent integer not null default 0 check (progress_percent between 0 and 100),
    created_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    error_message text
    );

create index if not exists idx_scan_jobs_library_id on scan_jobs(library_id);
create index if not exists idx_scan_jobs_status on scan_jobs(status);

create table if not exists scan_job_groups (
                                               id bigint generated by default as identity primary key,
    scan_job_id bigint not null references scan_jobs(id) on delete cascade,
    group_key text not null,
    file_count integer not null check (file_count > 0),
    local_analyzed boolean not null default false,
    local_committed boolean not null default false,
    remote_completed boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (scan_job_id, group_key)
    );

create index if not exists idx_scan_job_groups_scan_job_id on scan_job_groups(scan_job_id);

create table if not exists notifications (
                                             id bigint generated by default as identity primary key,
    category varchar(32) not null,
    notification_type varchar(64) not null,
    severity varchar(16) not null,
    audience varchar(16) not null,
    library_id bigint references libraries(id) on delete cascade,
    user_id bigint references users(id) on delete cascade,
    source_key text not null unique,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (severity in ('info', 'success', 'warning', 'error')),
    check (audience in ('server', 'admin', 'library', 'user')),
    check (
        (audience in ('server', 'admin') and library_id is null and user_id is null)
        or (audience = 'library' and library_id is not null and user_id is null)
        or (audience = 'user' and library_id is null and user_id is not null)
    )
    );

create index if not exists idx_notifications_created_at on notifications(created_at desc);
create index if not exists idx_notifications_category on notifications(category, created_at desc);
create index if not exists idx_notifications_audience on notifications(audience, created_at desc);
create index if not exists idx_notifications_library_id on notifications(library_id, created_at desc);
create index if not exists idx_notifications_user_id on notifications(user_id, created_at desc);

create table if not exists notification_reads (
                                                notification_id bigint not null references notifications(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    read_at timestamptz not null default now(),
    primary key (notification_id, user_id)
    );

create index if not exists idx_notification_reads_user_id on notification_reads(user_id, read_at desc);

create table if not exists background_jobs (
                                               id bigint generated by default as identity primary key,
                                               job_type varchar(64) not null,
    related_scan_job_id bigint references scan_jobs(id) on delete cascade,
    payload jsonb not null,
    status varchar(32) not null default 'pending', -- pending / running / succeeded / failed
    attempt_count integer not null default 0,
    max_attempts integer not null default 3,
    run_after timestamptz not null default now(),
    locked_by varchar(128),
    locked_at timestamptz,
    lease_expires_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    finished_at timestamptz,
    check (status in ('pending', 'running', 'succeeded', 'failed')),
    check (attempt_count >= 0),
    check (max_attempts > 0)
    );

create index if not exists idx_background_jobs_claim
    on background_jobs(status, run_after, lease_expires_at, created_at);
create index if not exists idx_background_jobs_related_scan_job_id
    on background_jobs(related_scan_job_id);
create unique index if not exists idx_background_jobs_unique_scan_job
    on background_jobs(related_scan_job_id)
    where related_scan_job_id is not null;

create table if not exists media_items (
                                           id bigint generated by default as identity primary key,
                                           library_id bigint not null references libraries(id) on delete cascade,
    media_type varchar(32) not null, -- movie / series / episode
    title text not null,
    source_title text not null,
    original_title text,
    sort_title text,
    metadata_provider varchar(32),
    metadata_provider_item_id bigint,
    metadata_status varchar(32) not null default 'skipped', -- pending / matched / unmatched / failed / skipped
    metadata_failure_reason varchar(64),
    remote_media_type varchar(32), -- movie / series
    year integer,
    imdb_rating varchar(8),
    country text,
    genres text,
    studio text,
    overview text,
    poster_path text,
    backdrop_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(id, library_id)
    );

create index if not exists idx_media_items_library_id on media_items(library_id);
create index if not exists idx_media_items_media_type on media_items(media_type);
create index if not exists idx_media_items_metadata_status on media_items(metadata_status);
create index if not exists idx_media_items_title on media_items(title);

create table if not exists seasons (
                                       id bigint generated by default as identity primary key,
                                       series_id bigint not null references media_items(id) on delete cascade,
    season_number integer not null,
    title text,
    overview text,
    poster_path text,
    backdrop_path text,
    intro_start_seconds integer,
    intro_end_seconds integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(series_id, season_number)
    );

create index if not exists idx_seasons_series_id on seasons(series_id);

create table if not exists episodes (
                                        id bigint generated by default as identity primary key,
                                        media_item_id bigint not null references media_items(id) on delete cascade,
    series_id bigint not null references media_items(id) on delete cascade,
    season_id bigint not null references seasons(id) on delete cascade,
    episode_number integer not null,
    title text not null,
    intro_start_seconds integer,
    intro_end_seconds integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(season_id, episode_number)
    );

alter table seasons add column if not exists intro_start_seconds integer;
alter table seasons add column if not exists intro_end_seconds integer;
alter table episodes add column if not exists intro_start_seconds integer;
alter table episodes add column if not exists intro_end_seconds integer;

create index if not exists idx_episodes_series_id on episodes(series_id);
create index if not exists idx_episodes_season_id on episodes(season_id);

create table if not exists series_episode_outline_cache (
    series_media_item_id bigint primary key references media_items(id) on delete cascade,
    outline_json text not null,
    fetched_at timestamptz not null default now(),
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
    );

create index if not exists idx_series_episode_outline_cache_expires_at
    on series_episode_outline_cache(expires_at);

create table if not exists media_item_cast_cache (
    media_item_id bigint primary key references media_items(id) on delete cascade,
    fetched_at timestamptz not null default now(),
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
    );

create index if not exists idx_media_item_cast_cache_expires_at
    on media_item_cast_cache(expires_at);

create table if not exists media_item_cast_members (
    id bigint generated by default as identity primary key,
    media_item_id bigint not null references media_items(id) on delete cascade,
    sort_order integer not null,
    provider_person_id bigint,
    name text not null,
    character_name text,
    profile_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_media_item_cast_members_media_item_id
    on media_item_cast_members(media_item_id);
create index if not exists idx_media_item_cast_members_media_item_sort_order
    on media_item_cast_members(media_item_id, sort_order);

create table if not exists media_files (
                                           id bigint generated by default as identity primary key,
                                           library_id bigint not null,
    media_item_id bigint not null,
    file_path text not null,
    container varchar(64),
    file_size bigint not null,
    duration_seconds integer,
    video_title text,
    video_codec varchar(64),
    video_profile varchar(128),
    video_level varchar(32),
    audio_codec varchar(64),
    width integer,
    height integer,
    bitrate bigint,
    video_bitrate bigint,
    video_frame_rate double precision,
    video_aspect_ratio varchar(32),
    video_scan_type varchar(32),
    video_color_primaries varchar(64),
    video_color_space varchar(64),
    video_color_transfer varchar(64),
    video_bit_depth integer,
    video_pixel_format varchar(64),
    video_reference_frames integer,
    technical_tags text[] not null default '{}'::text[],
    local_analysis_version integer not null default 1,
    scan_hash varchar(128),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(library_id, file_path),
    foreign key (media_item_id, library_id)
        references media_items(id, library_id)
        on delete cascade
    );

create index if not exists idx_media_files_library_id on media_files(library_id);
create index if not exists idx_media_files_media_item_id on media_files(media_item_id);

create table if not exists subtitle_files (
                                              id bigint generated by default as identity primary key,
                                              media_file_id bigint not null references media_files(id) on delete cascade,
    source_kind varchar(32) not null, -- external / embedded
    file_path text,
    stream_index integer,
    language varchar(32),
    subtitle_format varchar(32), -- srt / ass / vtt
    label text,
    is_default boolean not null default false,
    is_forced boolean not null default false,
    is_hearing_impaired boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_subtitle_files_media_file_id on subtitle_files(media_file_id);
create index if not exists idx_subtitle_files_source_kind on subtitle_files(source_kind);

create table if not exists audio_tracks (
                                             id bigint generated by default as identity primary key,
                                             media_file_id bigint not null references media_files(id) on delete cascade,
    stream_index integer not null,
    language varchar(32),
    audio_codec varchar(64),
    label text,
    channel_layout varchar(64),
    channels integer,
    bitrate bigint,
    sample_rate integer,
    is_default boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(media_file_id, stream_index)
    );

create index if not exists idx_audio_tracks_media_file_id on audio_tracks(media_file_id);
create index if not exists idx_audio_tracks_stream_index on audio_tracks(stream_index);

create table if not exists playback_progress (
                                                 id bigint generated by default as identity primary key,
                                                 user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint not null references media_files(id) on delete cascade,
    position_seconds integer not null default 0,
    duration_seconds integer,
    last_watched_at timestamptz not null default now(),
    is_finished boolean not null default false,
    unique(user_id, media_file_id)
    );

create index if not exists idx_playback_progress_user_id on playback_progress(user_id);
create index if not exists idx_playback_progress_last_watched_at on playback_progress(last_watched_at desc);

create table if not exists continue_watching (
                                                 id bigint generated by default as identity primary key,
                                                 user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    last_played_media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint not null references media_files(id) on delete cascade,
    last_watched_at timestamptz not null default now(),
    unique(user_id, media_item_id)
    );

create index if not exists idx_continue_watching_user_last_watched
    on continue_watching(user_id, last_watched_at desc);

create table if not exists realtime_system_state (
                                                    singleton boolean primary key default true check (singleton),
    server_epoch text not null,
    created_at timestamptz not null default now()
    );

insert into realtime_system_state (singleton, server_epoch)
values (true, md5(random()::text || clock_timestamp()::text))
on conflict (singleton) do nothing;

create table if not exists realtime_revisions (
                                                resource_key text primary key,
    revision bigint not null default 1,
    updated_at timestamptz not null default now()
    );

create or replace function mova_bump_realtime_revision(target_resource_key text)
returns void
language plpgsql
as $$
begin
    insert into realtime_revisions (resource_key, revision, updated_at)
    values (target_resource_key, 1, now())
    on conflict (resource_key) do update
        set revision = realtime_revisions.revision + 1,
            updated_at = excluded.updated_at;

    perform pg_notify('mova_realtime', target_resource_key);
end;
$$;

create or replace function mova_notify_library_change()
returns trigger
language plpgsql
as $$
declare
    changed_library_id bigint;
begin
    if tg_op = 'DELETE' then
        changed_library_id := old.id;
    else
        changed_library_id := new.id;
    end if;
    if tg_op = 'INSERT' then
        perform mova_bump_realtime_revision('admin:libraries');
    elsif tg_op = 'UPDATE' then
        perform mova_bump_realtime_revision('library:' || changed_library_id || ':settings');
    else
        perform mova_bump_realtime_revision('admin:libraries');
        perform mova_bump_realtime_revision('library:' || changed_library_id || ':settings');
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create trigger libraries_realtime_revision
after insert or update or delete on libraries
for each row execute function mova_notify_library_change();

create or replace function mova_notify_catalog_change()
returns trigger
language plpgsql
as $$
declare
    changed_library_id bigint;
begin
    if current_setting('mova.defer_catalog_revision', true) = 'on' then
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    if tg_op = 'DELETE' then
        changed_library_id := old.library_id;
    else
        changed_library_id := new.library_id;
    end if;
    perform mova_bump_realtime_revision('library:' || changed_library_id || ':catalog');
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create trigger media_items_realtime_revision
after insert or update or delete on media_items
for each row execute function mova_notify_catalog_change();

create trigger media_files_realtime_revision
after insert or update or delete on media_files
for each row execute function mova_notify_catalog_change();

create or replace function mova_notify_series_catalog_change()
returns trigger
language plpgsql
as $$
declare
    changed_series_id bigint;
    changed_library_id bigint;
begin
    if current_setting('mova.defer_catalog_revision', true) = 'on' then
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    if tg_op = 'DELETE' then
        changed_series_id := old.series_id;
    else
        changed_series_id := new.series_id;
    end if;
    select library_id into changed_library_id
    from media_items
    where id = changed_series_id;

    if changed_library_id is not null then
        perform mova_bump_realtime_revision('library:' || changed_library_id || ':catalog');
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create trigger seasons_realtime_revision
after insert or update or delete on seasons
for each row execute function mova_notify_series_catalog_change();

create trigger episodes_realtime_revision
after insert or update or delete on episodes
for each row execute function mova_notify_series_catalog_change();

create or replace function mova_notify_continue_watching_change()
returns trigger
language plpgsql
as $$
declare
    changed_user_id bigint;
begin
    if tg_op = 'DELETE' then
        changed_user_id := old.user_id;
    else
        changed_user_id := new.user_id;
    end if;
    perform mova_bump_realtime_revision('user:' || changed_user_id || ':continue-watching');
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create trigger continue_watching_realtime_revision
after insert or update or delete on continue_watching
for each row execute function mova_notify_continue_watching_change();

create or replace function mova_notify_user_change()
returns trigger
language plpgsql
as $$
declare
    changed_user_id bigint;
begin
    if tg_op = 'DELETE' then
        changed_user_id := old.id;
    else
        changed_user_id := new.id;
    end if;
    perform mova_bump_realtime_revision('admin:users');
    perform mova_bump_realtime_revision('user:' || changed_user_id || ':profile');

    if tg_op = 'DELETE' then
        perform mova_bump_realtime_revision('session:user:' || changed_user_id);
    elsif tg_op = 'UPDATE'
          and (new.role is distinct from old.role
               or new.is_enabled is distinct from old.is_enabled
               or new.password_hash is distinct from old.password_hash) then
        perform mova_bump_realtime_revision('session:user:' || changed_user_id);
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create trigger users_realtime_revision
after insert or update or delete on users
for each row execute function mova_notify_user_change();

create or replace function mova_notify_user_library_access_change()
returns trigger
language plpgsql
as $$
declare
    changed_user_id bigint;
begin
    if tg_op = 'DELETE' then
        changed_user_id := old.user_id;
    else
        changed_user_id := new.user_id;
    end if;
    perform mova_bump_realtime_revision('user:' || changed_user_id || ':libraries');
    perform mova_bump_realtime_revision('session:user:' || changed_user_id);
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create trigger user_library_access_realtime_revision
after insert or delete on user_library_access
for each row execute function mova_notify_user_library_access_change();

create or replace function mova_notify_scan_change()
returns trigger
language plpgsql
as $$
begin
    if tg_op = 'INSERT' or new.status is distinct from old.status then
        perform mova_bump_realtime_revision('library:' || new.library_id || ':scan');
    end if;
    return new;
end;
$$;

create trigger scan_jobs_realtime_revision_insert
after insert on scan_jobs
for each row execute function mova_notify_scan_change();

create trigger scan_jobs_realtime_revision_status
after update of status on scan_jobs
for each row execute function mova_notify_scan_change();
