create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     username varchar(254) not null unique,
    nickname varchar(128) not null,
    password_hash varchar(255) not null,
    role varchar(32) not null, -- admin / viewer
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists libraries (
                                         id bigint generated by default as identity primary key,
                                         name varchar(128) not null,
    description text,
    library_type varchar(32) not null, -- mixed / movie / series
    metadata_language varchar(32) not null default 'zh-CN',
    root_path text not null,
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists user_library_access (
                                                   user_id bigint not null references users(id) on delete cascade,
    library_id bigint not null references libraries(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, library_id)
    );

create index if not exists idx_user_library_access_library_id on user_library_access(library_id);

create table if not exists user_sessions (
                                             token varchar(128) primary key,
    user_id bigint not null references users(id) on delete cascade,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
    );

create index if not exists idx_user_sessions_user_id on user_sessions(user_id);
create index if not exists idx_user_sessions_expires_at on user_sessions(expires_at);

create table if not exists native_client_sessions (
                                                      id bigint generated by default as identity primary key,
                                                      user_id bigint not null references users(id) on delete cascade,
    access_token_hash varchar(128) not null unique,
    refresh_token_hash varchar(128) not null unique,
    access_token_expires_at timestamptz not null,
    refresh_token_expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_used_at timestamptz not null default now(),
    user_agent text,
    device_name varchar(128),
    client_type varchar(32) not null default 'native'
    );

create index if not exists idx_native_client_sessions_user_id on native_client_sessions(user_id);
create index if not exists idx_native_client_sessions_access_token_hash on native_client_sessions(access_token_hash);
create index if not exists idx_native_client_sessions_refresh_token_hash on native_client_sessions(refresh_token_hash);
create index if not exists idx_native_client_sessions_refresh_token_expires_at on native_client_sessions(refresh_token_expires_at);
create index if not exists idx_native_client_sessions_revoked_at on native_client_sessions(revoked_at);

create table if not exists native_client_used_refresh_tokens (
                                                                 token_hash varchar(128) primary key,
                                                                 session_id bigint not null references native_client_sessions(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now()
    );

create index if not exists idx_native_client_used_refresh_tokens_session_id on native_client_used_refresh_tokens(session_id);
create index if not exists idx_native_client_used_refresh_tokens_user_id on native_client_used_refresh_tokens(user_id);

create table if not exists scan_jobs (
                                         id bigint generated by default as identity primary key,
                                         library_id bigint not null references libraries(id) on delete cascade,
    status varchar(32) not null, -- pending / running / success / failed
    total_files integer not null default 0,
    scanned_files integer not null default 0,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    error_message text
    );

create index if not exists idx_scan_jobs_library_id on scan_jobs(library_id);
create index if not exists idx_scan_jobs_status on scan_jobs(status);

create table if not exists media_items (
                                           id bigint generated by default as identity primary key,
                                           library_id bigint not null references libraries(id) on delete cascade,
    media_type varchar(32) not null, -- movie / series / episode
    title text not null,
    source_title text not null,
    original_title text,
    sort_title text,
    metadata_provider varchar(32),
    metadata_provider_item_id bigint,
    metadata_status varchar(32) not null default 'skipped', -- matched / unmatched / failed / skipped
    metadata_failure_reason varchar(64),
    remote_media_type varchar(32), -- movie / series
    year integer,
    imdb_rating varchar(8),
    country text,
    genres text,
    studio text,
    overview text,
    poster_path text,
    backdrop_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(id, library_id)
    );

create index if not exists idx_media_items_library_id on media_items(library_id);
create index if not exists idx_media_items_media_type on media_items(media_type);
create index if not exists idx_media_items_metadata_status on media_items(metadata_status);
create index if not exists idx_media_items_title on media_items(title);

create table if not exists seasons (
                                       id bigint generated by default as identity primary key,
                                       series_id bigint not null references media_items(id) on delete cascade,
    season_number integer not null,
    title text,
    overview text,
    poster_path text,
    backdrop_path text,
    intro_start_seconds integer,
    intro_end_seconds integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(series_id, season_number)
    );

create index if not exists idx_seasons_series_id on seasons(series_id);

create table if not exists episodes (
                                        id bigint generated by default as identity primary key,
                                        media_item_id bigint not null references media_items(id) on delete cascade,
    series_id bigint not null references media_items(id) on delete cascade,
    season_id bigint not null references seasons(id) on delete cascade,
    episode_number integer not null,
    title text not null,
    intro_start_seconds integer,
    intro_end_seconds integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(season_id, episode_number)
    );

alter table seasons add column if not exists intro_start_seconds integer;
alter table seasons add column if not exists intro_end_seconds integer;
alter table episodes add column if not exists intro_start_seconds integer;
alter table episodes add column if not exists intro_end_seconds integer;

create index if not exists idx_episodes_series_id on episodes(series_id);
create index if not exists idx_episodes_season_id on episodes(season_id);

create table if not exists series_episode_outline_cache (
    series_media_item_id bigint primary key references media_items(id) on delete cascade,
    outline_json text not null,
    fetched_at timestamptz not null default now(),
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
    );

create index if not exists idx_series_episode_outline_cache_expires_at
    on series_episode_outline_cache(expires_at);

create table if not exists media_item_cast_cache (
    media_item_id bigint primary key references media_items(id) on delete cascade,
    fetched_at timestamptz not null default now(),
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
    );

create index if not exists idx_media_item_cast_cache_expires_at
    on media_item_cast_cache(expires_at);

create table if not exists media_item_cast_members (
    id bigint generated by default as identity primary key,
    media_item_id bigint not null references media_items(id) on delete cascade,
    sort_order integer not null,
    provider_person_id bigint,
    name text not null,
    character_name text,
    profile_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_media_item_cast_members_media_item_id
    on media_item_cast_members(media_item_id);
create index if not exists idx_media_item_cast_members_media_item_sort_order
    on media_item_cast_members(media_item_id, sort_order);

create table if not exists media_files (
                                           id bigint generated by default as identity primary key,
                                           library_id bigint not null,
    media_item_id bigint not null,
    file_path text not null,
    container varchar(64),
    file_size bigint not null,
    duration_seconds integer,
    video_title text,
    video_codec varchar(64),
    video_profile varchar(128),
    video_level varchar(32),
    audio_codec varchar(64),
    width integer,
    height integer,
    bitrate bigint,
    video_bitrate bigint,
    video_frame_rate double precision,
    video_aspect_ratio varchar(32),
    video_scan_type varchar(32),
    video_color_primaries varchar(64),
    video_color_space varchar(64),
    video_color_transfer varchar(64),
    video_bit_depth integer,
    video_pixel_format varchar(64),
    video_reference_frames integer,
    technical_tags text[] not null default '{}'::text[],
    local_analysis_version integer not null default 1,
    scan_hash varchar(128),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(library_id, file_path),
    foreign key (media_item_id, library_id)
        references media_items(id, library_id)
        on delete cascade
    );

create index if not exists idx_media_files_library_id on media_files(library_id);
create index if not exists idx_media_files_media_item_id on media_files(media_item_id);

create table if not exists subtitle_files (
                                              id bigint generated by default as identity primary key,
                                              media_file_id bigint not null references media_files(id) on delete cascade,
    source_kind varchar(32) not null, -- external / embedded
    file_path text,
    stream_index integer,
    language varchar(32),
    subtitle_format varchar(32), -- srt / ass / vtt
    label text,
    is_default boolean not null default false,
    is_forced boolean not null default false,
    is_hearing_impaired boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_subtitle_files_media_file_id on subtitle_files(media_file_id);
create index if not exists idx_subtitle_files_source_kind on subtitle_files(source_kind);

create table if not exists audio_tracks (
                                             id bigint generated by default as identity primary key,
                                             media_file_id bigint not null references media_files(id) on delete cascade,
    stream_index integer not null,
    language varchar(32),
    audio_codec varchar(64),
    label text,
    channel_layout varchar(64),
    channels integer,
    bitrate bigint,
    sample_rate integer,
    is_default boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(media_file_id, stream_index)
    );

create index if not exists idx_audio_tracks_media_file_id on audio_tracks(media_file_id);
create index if not exists idx_audio_tracks_stream_index on audio_tracks(stream_index);

create table if not exists playback_progress (
                                                 id bigint generated by default as identity primary key,
                                                 user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint not null references media_files(id) on delete cascade,
    position_seconds integer not null default 0,
    duration_seconds integer,
    last_watched_at timestamptz not null default now(),
    is_finished boolean not null default false,
    unique(user_id, media_file_id)
    );

create index if not exists idx_playback_progress_user_id on playback_progress(user_id);
create index if not exists idx_playback_progress_last_watched_at on playback_progress(last_watched_at desc);

create table if not exists continue_watching (
                                                 id bigint generated by default as identity primary key,
                                                 user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    last_played_media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint not null references media_files(id) on delete cascade,
    last_watched_at timestamptz not null default now(),
    unique(user_id, media_item_id)
    );

create index if not exists idx_continue_watching_user_last_watched
    on continue_watching(user_id, last_watched_at desc);
