create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     username varchar(64) not null unique,
    password_hash varchar(255) not null,
    role varchar(32) not null, -- admin / viewer
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists libraries (
                                         id bigint generated by default as identity primary key,
                                         name varchar(128) not null,
    description text,
    library_type varchar(32) not null, -- mixed / movie / series
    metadata_language varchar(32) not null default 'zh-CN',
    root_path text not null,
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists user_library_access (
                                                   user_id bigint not null references users(id) on delete cascade,
    library_id bigint not null references libraries(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, library_id)
    );

create index if not exists idx_user_library_access_library_id on user_library_access(library_id);

create table if not exists user_sessions (
                                             token varchar(128) primary key,
    user_id bigint not null references users(id) on delete cascade,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
    );

create index if not exists idx_user_sessions_user_id on user_sessions(user_id);
create index if not exists idx_user_sessions_expires_at on user_sessions(expires_at);

create table if not exists scan_jobs (
                                         id bigint generated by default as identity primary key,
                                         library_id bigint not null references libraries(id) on delete cascade,
    status varchar(32) not null, -- pending / running / success / failed
    total_files integer not null default 0,
    scanned_files integer not null default 0,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    error_message text
    );

create index if not exists idx_scan_jobs_library_id on scan_jobs(library_id);
create index if not exists idx_scan_jobs_status on scan_jobs(status);

create table if not exists media_items (
                                           id bigint generated by default as identity primary key,
                                           library_id bigint not null references libraries(id) on delete cascade,
    media_type varchar(32) not null, -- movie / series / episode
    title varchar(512) not null,
    source_title varchar(512) not null,
    original_title varchar(512),
    sort_title varchar(512),
    metadata_provider varchar(32),
    metadata_provider_item_id bigint,
    year integer,
    overview text,
    poster_path text,
    backdrop_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(id, library_id)
    );

create index if not exists idx_media_items_library_id on media_items(library_id);
create index if not exists idx_media_items_media_type on media_items(media_type);
create index if not exists idx_media_items_title on media_items(title);

create table if not exists seasons (
                                       id bigint generated by default as identity primary key,
                                       series_id bigint not null references media_items(id) on delete cascade,
    season_number integer not null,
    title varchar(255),
    overview text,
    poster_path text,
    backdrop_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(series_id, season_number)
    );

create index if not exists idx_seasons_series_id on seasons(series_id);

create table if not exists episodes (
                                        id bigint generated by default as identity primary key,
                                        media_item_id bigint not null references media_items(id) on delete cascade,
    series_id bigint not null references media_items(id) on delete cascade,
    season_id bigint not null references seasons(id) on delete cascade,
    episode_number integer not null,
    title varchar(255) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(season_id, episode_number)
    );

create index if not exists idx_episodes_series_id on episodes(series_id);
create index if not exists idx_episodes_season_id on episodes(season_id);

create table if not exists series_episode_outline_cache (
    series_media_item_id bigint primary key references media_items(id) on delete cascade,
    outline_json text not null,
    fetched_at timestamptz not null default now(),
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
    );

create index if not exists idx_series_episode_outline_cache_expires_at
    on series_episode_outline_cache(expires_at);

create table if not exists media_item_cast_cache (
    media_item_id bigint primary key references media_items(id) on delete cascade,
    fetched_at timestamptz not null default now(),
    expires_at timestamptz not null,
    updated_at timestamptz not null default now()
    );

create index if not exists idx_media_item_cast_cache_expires_at
    on media_item_cast_cache(expires_at);

create table if not exists media_item_cast_members (
    id bigint generated by default as identity primary key,
    media_item_id bigint not null references media_items(id) on delete cascade,
    sort_order integer not null,
    provider_person_id bigint,
    name varchar(255) not null,
    character_name varchar(255),
    profile_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_media_item_cast_members_media_item_id
    on media_item_cast_members(media_item_id);
create index if not exists idx_media_item_cast_members_media_item_sort_order
    on media_item_cast_members(media_item_id, sort_order);

create table if not exists media_files (
                                           id bigint generated by default as identity primary key,
                                           library_id bigint not null,
    media_item_id bigint not null,
    file_path text not null,
    container varchar(64),
    file_size bigint not null,
    duration_seconds integer,
    video_codec varchar(64),
    audio_codec varchar(64),
    width integer,
    height integer,
    bitrate bigint,
    scan_hash varchar(128),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(library_id, file_path),
    foreign key (media_item_id, library_id)
        references media_items(id, library_id)
        on delete cascade
    );

create index if not exists idx_media_files_library_id on media_files(library_id);
create index if not exists idx_media_files_media_item_id on media_files(media_item_id);

create table if not exists subtitle_files (
                                              id bigint generated by default as identity primary key,
                                              media_file_id bigint not null references media_files(id) on delete cascade,
    source_kind varchar(32) not null, -- external / embedded
    file_path text,
    stream_index integer,
    language varchar(32),
    subtitle_format varchar(32), -- srt / ass / vtt
    label varchar(255),
    is_default boolean not null default false,
    is_forced boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_subtitle_files_media_file_id on subtitle_files(media_file_id);
create index if not exists idx_subtitle_files_source_kind on subtitle_files(source_kind);

create table if not exists playback_progress (
                                                 id bigint generated by default as identity primary key,
                                                 user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint not null references media_files(id) on delete cascade,
    position_seconds integer not null default 0,
    duration_seconds integer,
    last_watched_at timestamptz not null default now(),
    is_finished boolean not null default false,
    unique(user_id, media_file_id)
    );

create index if not exists idx_playback_progress_user_id on playback_progress(user_id);
create index if not exists idx_playback_progress_last_watched_at on playback_progress(last_watched_at desc);

create table if not exists watch_history (
                                             id bigint generated by default as identity primary key,
                                             user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint not null references media_files(id) on delete cascade,
    position_seconds integer not null default 0,
    duration_seconds integer,
    started_at timestamptz not null default now(),
    last_watched_at timestamptz not null default now(),
    ended_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create index if not exists idx_watch_history_user_id on watch_history(user_id);
create index if not exists idx_watch_history_last_watched_at on watch_history(last_watched_at desc);
create index if not exists idx_watch_history_user_media_file_open
    on watch_history(user_id, media_file_id, last_watched_at desc)
    where ended_at is null;
