-- Persist normalized local NFO metadata without treating the sidecar XML as
-- the public contract. Local values coexist with provider-owned values and
-- survive remote metadata refreshes.

alter table media_items
    add column if not exists tagline text,
    add column if not exists premiere_date date,
    add column if not exists content_rating text;

alter table media_item_external_ids
    add column if not exists retrieved_via varchar(32) not null default 'tmdb';

alter table media_item_external_ids
    drop constraint if exists media_item_external_ids_pkey;

alter table media_item_external_ids
    add constraint media_item_external_ids_pkey
        primary key (media_item_id, provider, retrieved_via),
    add constraint media_item_external_ids_retrieved_via_format
        check (retrieved_via ~ '^[a-z0-9][a-z0-9_]*$');

alter table media_item_ratings
    drop constraint if exists media_item_ratings_media_item_id_source_kind_key;

alter table media_item_ratings
    add constraint media_item_ratings_media_item_source_kind_via_key
        unique (media_item_id, source, kind, retrieved_via),
    add constraint media_item_ratings_retrieved_via_format
        check (retrieved_via ~ '^[a-z0-9][a-z0-9_]*$');

create table if not exists media_local_metadata_sources (
    id bigint generated by default as identity primary key,
    library_id bigint not null references libraries(id) on delete cascade,
    media_item_id bigint not null,
    source_path text not null,
    document_type varchar(32) not null,
    target_media_type varchar(32)
        generated always as (
            case document_type
                when 'movie' then 'movie'::varchar(32)
                when 'tvshow' then 'series'::varchar(32)
                when 'episodedetails' then 'episode'::varchar(32)
                else null::varchar(32)
            end
        ) stored,
    schema_version integer not null default 1,
    is_locked boolean not null default false,
    is_selected boolean not null default false,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (library_id, source_path),
    unique (id, media_item_id),
    check (btrim(source_path) <> ''),
    check (document_type in ('movie', 'tvshow', 'episodedetails')),
    check (schema_version > 0),
    check (jsonb_typeof(payload) = 'object'),
    foreign key (media_item_id, library_id, target_media_type)
        references media_items(id, library_id, media_type)
        on delete cascade
);

create index if not exists idx_media_local_metadata_sources_media_item
    on media_local_metadata_sources(media_item_id);

create unique index if not exists idx_media_local_metadata_sources_selected_media_item
    on media_local_metadata_sources(media_item_id)
    where is_selected;

alter table media_item_external_ids
    add column local_metadata_source_id bigint,
    add constraint media_item_external_ids_local_metadata_source_fk
        foreign key (local_metadata_source_id, media_item_id)
        references media_local_metadata_sources(id, media_item_id)
        on delete cascade,
    add constraint media_item_external_ids_local_metadata_source_owner
        check (
            (retrieved_via = 'nfo' and local_metadata_source_id is not null)
            or (retrieved_via <> 'nfo' and local_metadata_source_id is null)
        );

create index if not exists idx_media_item_external_ids_local_metadata_source
    on media_item_external_ids(local_metadata_source_id, media_item_id)
    where local_metadata_source_id is not null;

alter table media_item_ratings
    add column local_metadata_source_id bigint,
    add constraint media_item_ratings_local_metadata_source_fk
        foreign key (local_metadata_source_id, media_item_id)
        references media_local_metadata_sources(id, media_item_id)
        on delete cascade,
    add constraint media_item_ratings_local_metadata_source_owner
        check (
            (retrieved_via = 'nfo' and local_metadata_source_id is not null)
            or (retrieved_via <> 'nfo' and local_metadata_source_id is null)
        );

create index if not exists idx_media_item_ratings_local_metadata_source
    on media_item_ratings(local_metadata_source_id, media_item_id)
    where local_metadata_source_id is not null;

create table if not exists media_item_credits (
    id bigint generated by default as identity primary key,
    media_item_id bigint not null references media_items(id) on delete cascade,
    local_metadata_source_id bigint,
    credit_type varchar(32) not null,
    retrieved_via varchar(32) not null,
    sort_order integer not null,
    person_provider varchar(32),
    provider_person_id varchar(128),
    name text not null,
    role text,
    profile_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (credit_type in ('actor', 'director', 'writer')),
    check (retrieved_via ~ '^[a-z0-9][a-z0-9_]*$'),
    check (sort_order >= 0),
    check (btrim(name) <> ''),
    check (person_provider is null or person_provider ~ '^[a-z0-9][a-z0-9_]*$'),
    check (provider_person_id is null or btrim(provider_person_id) <> ''),
    check ((person_provider is null) = (provider_person_id is null)),
    check (
        (retrieved_via = 'nfo' and local_metadata_source_id is not null)
        or (retrieved_via <> 'nfo' and local_metadata_source_id is null)
    ),
    foreign key (local_metadata_source_id, media_item_id)
        references media_local_metadata_sources(id, media_item_id)
        on delete cascade
);

create index if not exists idx_media_item_credits_item_type_source_order
    on media_item_credits(media_item_id, credit_type, retrieved_via, sort_order, id);

create index if not exists idx_media_item_credits_local_metadata_source
    on media_item_credits(local_metadata_source_id, media_item_id)
    where local_metadata_source_id is not null;

-- Binding changes only invalidate provider-owned metadata. Local NFO and
-- future manual projections must survive a TMDB rebind or retention expiry.
create or replace function mova_sync_tmdb_revalidation_binding()
returns trigger
language plpgsql
as $$
declare
    binding_time timestamptz := clock_timestamp();
    previous_snapshot jsonb;
    cleanup_paths text[];
    previous_tmdb_binding boolean := false;
    current_tmdb_binding boolean;
    stable_matched_tmdb_binding boolean := false;
    binding_changed boolean := false;
    invalidate_provider_cache boolean := false;
    retention_expiry_managed boolean :=
        coalesce(current_setting('mova.tmdb_retention_expiry', true), 'off') = 'on';
begin
    current_tmdb_binding :=
        new.media_type in ('movie', 'series')
        and new.metadata_provider = 'tmdb'
        and new.metadata_provider_item_id is not null;

    if tg_op = 'UPDATE' then
        previous_tmdb_binding :=
            old.media_type in ('movie', 'series')
            and old.metadata_provider = 'tmdb'
            and old.metadata_provider_item_id is not null;
        stable_matched_tmdb_binding :=
            previous_tmdb_binding
            and current_tmdb_binding
            and old.metadata_status = 'matched'
            and new.metadata_status = 'matched'
            and new.media_type is not distinct from old.media_type
            and new.metadata_provider_item_id
                is not distinct from old.metadata_provider_item_id;
        binding_changed :=
            previous_tmdb_binding
            and (
                not current_tmdb_binding
                or new.media_type is distinct from old.media_type
                or new.metadata_provider_item_id
                    is distinct from old.metadata_provider_item_id
            );
        invalidate_provider_cache :=
            (previous_tmdb_binding or current_tmdb_binding)
            and not stable_matched_tmdb_binding;

        if invalidate_provider_cache and not retention_expiry_managed then
            select revalidation.remote_snapshot
            into previous_snapshot
            from tmdb_metadata_revalidations revalidation
            where revalidation.media_item_id = old.id;

            with candidate_paths(path) as (
                select old.poster_path where binding_changed
                union all
                select old.backdrop_path where binding_changed
                union all
                select old.logo_path where binding_changed
                union all
                select season.poster_path
                from seasons season
                where binding_changed and season.series_id = old.id
                union all
                select season.backdrop_path
                from seasons season
                where binding_changed and season.series_id = old.id
                union all
                select episode_item.poster_path
                from seasons season
                join episodes episode on episode.season_id = season.id
                join media_items episode_item on episode_item.id = episode.media_item_id
                where binding_changed and season.series_id = old.id
                union all
                select episode_item.backdrop_path
                from seasons season
                join episodes episode on episode.season_id = season.id
                join media_items episode_item on episode_item.id = episode.media_item_id
                where binding_changed and season.series_id = old.id
                union all
                select member.profile_path
                from media_item_cast_members member
                where member.media_item_id = old.id
                union all
                select value #>> '{}'
                from jsonb_path_query(
                    coalesce(previous_snapshot, '{}'::jsonb),
                    '$.**.poster_path'
                ) value
                where binding_changed
                union all
                select value #>> '{}'
                from jsonb_path_query(
                    coalesce(previous_snapshot, '{}'::jsonb),
                    '$.**.backdrop_path'
                ) value
                where binding_changed
                union all
                select value #>> '{}'
                from jsonb_path_query(
                    coalesce(previous_snapshot, '{}'::jsonb),
                    '$.**.logo_path'
                ) value
                where binding_changed
                union all
                select value #>> '{}'
                from series_episode_outline_cache outline
                cross join lateral jsonb_path_query(
                    outline.outline_json::jsonb,
                    '$.**.poster_path'
                ) value
                where outline.series_media_item_id = old.id
                union all
                select value #>> '{}'
                from series_episode_outline_cache outline
                cross join lateral jsonb_path_query(
                    outline.outline_json::jsonb,
                    '$.**.backdrop_path'
                ) value
                where outline.series_media_item_id = old.id
                union all
                select value #>> '{}'
                from series_episode_outline_cache outline
                cross join lateral jsonb_path_query(
                    outline.outline_json::jsonb,
                    '$.**.logo_path'
                ) value
                where outline.series_media_item_id = old.id
            ),
            cached_paths as (
                select distinct path
                from candidate_paths
                where path is not null
                  and btrim(path) <> ''
                  and position(
                        '/libraries/' || old.library_id::text || '/artwork/tmdb/'
                        in replace(path, chr(92), '/')
                      ) > 0
            )
            select array_agg(path order by path)
            into cleanup_paths
            from cached_paths;

            if coalesce(cardinality(cleanup_paths), 0) > 0 then
                insert into background_jobs (
                    job_type,
                    scope_type,
                    scope_id,
                    payload,
                    max_attempts
                )
                values (
                    'metadata.tmdb.artwork.cleanup',
                    'library',
                    old.library_id,
                    jsonb_build_object(
                        'library_id', old.library_id,
                        'media_item_id', old.id,
                        'artwork_paths', to_jsonb(cleanup_paths)
                    ),
                    2147483647
                );
            end if;

            delete from media_item_cast_cache where media_item_id = old.id;
            delete from series_episode_outline_cache where series_media_item_id = old.id;
        end if;

        if binding_changed and not retention_expiry_managed then
            delete from media_item_external_ids
            where media_item_id = old.id
              and retrieved_via not in ('nfo', 'manual');
            delete from media_item_ratings
            where media_item_id = old.id
              and retrieved_via not in ('nfo', 'manual');
        end if;
    end if;

    if current_tmdb_binding then
        insert into tmdb_metadata_revalidations (
            media_item_id,
            provider_item_id,
            next_attempt_at,
            retain_until
        )
        values (
            new.id,
            new.metadata_provider_item_id,
            binding_time + interval '150 days',
            binding_time + interval '180 days'
        )
        on conflict (media_item_id) do update
        set provider_item_id = excluded.provider_item_id,
            verified_at = null,
            last_attempt_at = null,
            next_attempt_at = excluded.next_attempt_at,
            retain_until = excluded.retain_until,
            consecutive_failures = 0,
            remote_snapshot = '{}'::jsonb,
            updated_at = binding_time
        where tmdb_metadata_revalidations.provider_item_id
              is distinct from excluded.provider_item_id
           or (
                tg_op = 'UPDATE'
                and new.media_type is distinct from old.media_type
              );
    else
        delete from tmdb_metadata_revalidations where media_item_id = new.id;
    end if;

    return new;
end;
$$;

create or replace function mova_ensure_tmdb_revalidation_state()
returns trigger
language plpgsql
as $$
declare
    binding_time timestamptz := clock_timestamp();
begin
    if new.provider <> 'tmdb' or new.retrieved_via in ('nfo', 'manual') then
        return new;
    end if;

    insert into tmdb_metadata_revalidations (
        media_item_id,
        provider_item_id,
        next_attempt_at,
        retain_until
    )
    select
        item.id,
        item.metadata_provider_item_id,
        binding_time + interval '150 days',
        binding_time + interval '180 days'
    from media_items item
    where item.id = new.media_item_id
      and item.media_type in ('movie', 'series')
      and item.metadata_provider = 'tmdb'
      and item.metadata_provider_item_id = new.external_id
    on conflict (media_item_id) do nothing;

    return new;
end;
$$;
