#!/usr/bin/env bash

set -euo pipefail

REPOSITORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CLASSIFIER="$REPOSITORY_ROOT/scripts/classify-release-only-pr.sh"
TEST_DIRECTORY="$(mktemp -d)"
trap 'rm -rf "$TEST_DIRECTORY"' EXIT

create_repository() {
  local repository="$1"

  mkdir -p "$repository"
  git -C "$repository" init --quiet
  git -C "$repository" config user.name test
  git -C "$repository" config user.email test@example.com
  cat >"$repository/Cargo.toml" <<'EOF'
[workspace]
members = ["crates/mova-domain"]

[workspace.package]
version = "1.4.0"
edition = "2021"
EOF
  cat >"$repository/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "mova-domain"
version = "1.4.0"

[[package]]
name = "mova-server"
version = "1.4.0"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
EOF
  mkdir -p "$repository/crates/mova-domain/src"
  printf '[package]\nname = "mova-domain"\nversion.workspace = true\n' \
    >"$repository/crates/mova-domain/Cargo.toml"
  printf 'pub struct Item;\n' >"$repository/crates/mova-domain/src/lib.rs"
  git -C "$repository" add .
  git -C "$repository" commit --quiet -m base
}

prepare_release() {
  local repository="$1"
  local version="${2:-1.5.0}"

  sed -i.bak 's/version = "1.4.0"/version = "'"$version"'"/' "$repository/Cargo.toml"
  rm "$repository/Cargo.toml.bak"
  sed -i.bak 's/version = "1.4.0"/version = "'"$version"'"/g' "$repository/Cargo.lock"
  rm "$repository/Cargo.lock.bak"
  mkdir -p "$repository/.github/release-notes"
  printf '# %s\n' "$version" >"$repository/.github/release-notes/$version.md"
  git -C "$repository" add .
  git -C "$repository" commit --quiet -m "chore(release): prepare $version"
}

classify() {
  local repository="$1"
  local base_sha="$2"
  local head_sha="$3"
  local title="$4"

  MOVA_REPOSITORY_ROOT="$repository" \
  MOVA_BASE_SHA="$base_sha" \
  MOVA_HEAD_SHA="$head_sha" \
  MOVA_PR_TITLE="$title" \
    "$CLASSIFIER" 2>/dev/null
}

assert_classification() {
  local expected="$1"
  local repository="$2"
  local base_sha="$3"
  local head_sha="$4"
  local title="$5"
  local actual

  actual="$(classify "$repository" "$base_sha" "$head_sha" "$title")"
  if [[ "$actual" != "$expected" ]]; then
    printf 'Expected classification %s, got %s for %s.\n' "$expected" "$actual" "$title" >&2
    exit 1
  fi
}

new_case() {
  local name="$1"
  local repository="$TEST_DIRECTORY/$name"

  create_repository "$repository"
  printf '%s\n' "$repository"
}

VALID_REPOSITORY="$(new_case valid)"
VALID_BASE="$(git -C "$VALID_REPOSITORY" rev-parse HEAD)"
prepare_release "$VALID_REPOSITORY"
VALID_HEAD="$(git -C "$VALID_REPOSITORY" rev-parse HEAD)"
assert_classification true "$VALID_REPOSITORY" "$VALID_BASE" "$VALID_HEAD" \
  'chore(release): prepare 1.5.0'
assert_classification true "$VALID_REPOSITORY" "$VALID_BASE" "$VALID_HEAD" \
  'chore(release): prepare 1.5.0 (#72)'
assert_classification false "$VALID_REPOSITORY" "$VALID_BASE" "$VALID_HEAD" \
  'chore(release): prepare 1.5.1'

STABLE_REPOSITORY="$(new_case stable-from-preview)"
sed -i.bak 's/version = "1.4.0"/version = "1.5.0-preview.1"/' "$STABLE_REPOSITORY/Cargo.toml"
rm "$STABLE_REPOSITORY/Cargo.toml.bak"
sed -i.bak 's/version = "1.4.0"/version = "1.5.0-preview.1"/g' "$STABLE_REPOSITORY/Cargo.lock"
rm "$STABLE_REPOSITORY/Cargo.lock.bak"
git -C "$STABLE_REPOSITORY" add Cargo.toml Cargo.lock
git -C "$STABLE_REPOSITORY" commit --quiet --amend --no-edit
STABLE_BASE="$(git -C "$STABLE_REPOSITORY" rev-parse HEAD)"
sed -i.bak 's/version = "1.5.0-preview.1"/version = "1.5.0"/' "$STABLE_REPOSITORY/Cargo.toml"
rm "$STABLE_REPOSITORY/Cargo.toml.bak"
sed -i.bak 's/version = "1.5.0-preview.1"/version = "1.5.0"/g' "$STABLE_REPOSITORY/Cargo.lock"
rm "$STABLE_REPOSITORY/Cargo.lock.bak"
git -C "$STABLE_REPOSITORY" add Cargo.toml Cargo.lock
git -C "$STABLE_REPOSITORY" commit --quiet -m 'prepare stable'
STABLE_HEAD="$(git -C "$STABLE_REPOSITORY" rev-parse HEAD)"
assert_classification true "$STABLE_REPOSITORY" "$STABLE_BASE" "$STABLE_HEAD" \
  'chore(release): prepare 1.5.0'

DOWNGRADE_REPOSITORY="$(new_case downgrade)"
DOWNGRADE_BASE="$(git -C "$DOWNGRADE_REPOSITORY" rev-parse HEAD)"
prepare_release "$DOWNGRADE_REPOSITORY" 1.3.0
DOWNGRADE_HEAD="$(git -C "$DOWNGRADE_REPOSITORY" rev-parse HEAD)"
assert_classification false "$DOWNGRADE_REPOSITORY" "$DOWNGRADE_BASE" "$DOWNGRADE_HEAD" \
  'chore(release): prepare 1.3.0'

BUILD_METADATA_REPOSITORY="$(new_case build-metadata)"
BUILD_METADATA_BASE="$(git -C "$BUILD_METADATA_REPOSITORY" rev-parse HEAD)"
prepare_release "$BUILD_METADATA_REPOSITORY" 1.5.0+build.1
BUILD_METADATA_HEAD="$(git -C "$BUILD_METADATA_REPOSITORY" rev-parse HEAD)"
assert_classification false \
  "$BUILD_METADATA_REPOSITORY" \
  "$BUILD_METADATA_BASE" \
  "$BUILD_METADATA_HEAD" \
  'chore(release): prepare 1.5.0+build.1'

SYMLINK_NOTES_REPOSITORY="$(new_case symlink-notes)"
SYMLINK_NOTES_BASE="$(git -C "$SYMLINK_NOTES_REPOSITORY" rev-parse HEAD)"
prepare_release "$SYMLINK_NOTES_REPOSITORY"
rm "$SYMLINK_NOTES_REPOSITORY/.github/release-notes/1.5.0.md"
ln -s ../../../Cargo.toml "$SYMLINK_NOTES_REPOSITORY/.github/release-notes/1.5.0.md"
git -C "$SYMLINK_NOTES_REPOSITORY" add .github/release-notes/1.5.0.md
git -C "$SYMLINK_NOTES_REPOSITORY" commit --quiet --amend --no-edit
SYMLINK_NOTES_HEAD="$(git -C "$SYMLINK_NOTES_REPOSITORY" rev-parse HEAD)"
assert_classification false \
  "$SYMLINK_NOTES_REPOSITORY" \
  "$SYMLINK_NOTES_BASE" \
  "$SYMLINK_NOTES_HEAD" \
  'chore(release): prepare 1.5.0'

NO_NOTES_REPOSITORY="$(new_case no-notes)"
NO_NOTES_BASE="$(git -C "$NO_NOTES_REPOSITORY" rev-parse HEAD)"
prepare_release "$NO_NOTES_REPOSITORY"
git -C "$NO_NOTES_REPOSITORY" rm --quiet .github/release-notes/1.5.0.md
git -C "$NO_NOTES_REPOSITORY" commit --quiet --amend --no-edit
NO_NOTES_HEAD="$(git -C "$NO_NOTES_REPOSITORY" rev-parse HEAD)"
assert_classification true "$NO_NOTES_REPOSITORY" "$NO_NOTES_BASE" "$NO_NOTES_HEAD" \
  'chore(release): prepare 1.5.0'

EXTRA_REPOSITORY="$(new_case extra-file)"
EXTRA_BASE="$(git -C "$EXTRA_REPOSITORY" rev-parse HEAD)"
prepare_release "$EXTRA_REPOSITORY"
printf 'changed\n' >>"$EXTRA_REPOSITORY/crates/mova-domain/src/lib.rs"
git -C "$EXTRA_REPOSITORY" add .
git -C "$EXTRA_REPOSITORY" commit --quiet --amend --no-edit
EXTRA_HEAD="$(git -C "$EXTRA_REPOSITORY" rev-parse HEAD)"
assert_classification false "$EXTRA_REPOSITORY" "$EXTRA_BASE" "$EXTRA_HEAD" \
  'chore(release): prepare 1.5.0'

MANIFEST_REPOSITORY="$(new_case manifest-extra)"
MANIFEST_BASE="$(git -C "$MANIFEST_REPOSITORY" rev-parse HEAD)"
prepare_release "$MANIFEST_REPOSITORY"
printf '\n[profile.release]\nlto = true\n' >>"$MANIFEST_REPOSITORY/Cargo.toml"
git -C "$MANIFEST_REPOSITORY" add Cargo.toml
git -C "$MANIFEST_REPOSITORY" commit --quiet --amend --no-edit
MANIFEST_HEAD="$(git -C "$MANIFEST_REPOSITORY" rev-parse HEAD)"
assert_classification false "$MANIFEST_REPOSITORY" "$MANIFEST_BASE" "$MANIFEST_HEAD" \
  'chore(release): prepare 1.5.0'

LOCK_REPOSITORY="$(new_case lock-extra)"
LOCK_BASE="$(git -C "$LOCK_REPOSITORY" rev-parse HEAD)"
prepare_release "$LOCK_REPOSITORY"
sed -i.bak 's/version = "1.0.0"/version = "1.0.1"/' "$LOCK_REPOSITORY/Cargo.lock"
rm "$LOCK_REPOSITORY/Cargo.lock.bak"
git -C "$LOCK_REPOSITORY" add Cargo.lock
git -C "$LOCK_REPOSITORY" commit --quiet --amend --no-edit
LOCK_HEAD="$(git -C "$LOCK_REPOSITORY" rev-parse HEAD)"
assert_classification false "$LOCK_REPOSITORY" "$LOCK_BASE" "$LOCK_HEAD" \
  'chore(release): prepare 1.5.0'

WRONG_LOCK_REPOSITORY="$(new_case wrong-lock-version)"
WRONG_LOCK_BASE="$(git -C "$WRONG_LOCK_REPOSITORY" rev-parse HEAD)"
prepare_release "$WRONG_LOCK_REPOSITORY"
awk '
  BEGIN { in_target = 0; changed = 0 }
  /^\[\[package\]\]$/ { in_target = 0 }
  /^name = "mova-domain"$/ { in_target = 1 }
  in_target && !changed && /^version = "1.5.0"$/ {
    print "version = \"1.5.1\""
    changed = 1
    next
  }
  { print }
' "$WRONG_LOCK_REPOSITORY/Cargo.lock" >"$WRONG_LOCK_REPOSITORY/Cargo.lock.bak"
mv "$WRONG_LOCK_REPOSITORY/Cargo.lock.bak" "$WRONG_LOCK_REPOSITORY/Cargo.lock"
git -C "$WRONG_LOCK_REPOSITORY" add Cargo.lock
git -C "$WRONG_LOCK_REPOSITORY" commit --quiet --amend --no-edit
WRONG_LOCK_HEAD="$(git -C "$WRONG_LOCK_REPOSITORY" rev-parse HEAD)"
assert_classification false "$WRONG_LOCK_REPOSITORY" "$WRONG_LOCK_BASE" "$WRONG_LOCK_HEAD" \
  'chore(release): prepare 1.5.0'

WRONG_NOTES_REPOSITORY="$(new_case wrong-notes)"
WRONG_NOTES_BASE="$(git -C "$WRONG_NOTES_REPOSITORY" rev-parse HEAD)"
prepare_release "$WRONG_NOTES_REPOSITORY"
git -C "$WRONG_NOTES_REPOSITORY" mv \
  .github/release-notes/1.5.0.md .github/release-notes/next.md
git -C "$WRONG_NOTES_REPOSITORY" commit --quiet --amend --no-edit
WRONG_NOTES_HEAD="$(git -C "$WRONG_NOTES_REPOSITORY" rev-parse HEAD)"
assert_classification false "$WRONG_NOTES_REPOSITORY" "$WRONG_NOTES_BASE" "$WRONG_NOTES_HEAD" \
  'chore(release): prepare 1.5.0'

SAME_REPOSITORY="$(new_case same-version)"
SAME_SHA="$(git -C "$SAME_REPOSITORY" rev-parse HEAD)"
assert_classification false "$SAME_REPOSITORY" "$SAME_SHA" "$SAME_SHA" \
  'chore(release): prepare 1.4.0'

INVALID_OUTPUT="$(
  MOVA_REPOSITORY_ROOT="$VALID_REPOSITORY" \
  MOVA_BASE_SHA=invalid \
  MOVA_HEAD_SHA="$VALID_HEAD" \
  MOVA_PR_TITLE='chore(release): prepare 1.5.0' \
    "$CLASSIFIER" 2>/dev/null
)"
[[ "$INVALID_OUTPUT" == false ]] || {
  echo 'Invalid input did not fail closed.' >&2
  exit 1
}

echo 'Release-only pull request classifier tests passed.'
